export const posts = [
  {
    id: 1,
    authorId: 1,
    claimerId: null,
    itemName: "Coffee",
    imageUrl: "www.hello.com",
    pickupCountry: "Ethiopia",
    deliveryCity: "Washington, DC",
  },
  {
    id: 2,
    authorId: 2,
    claimerId: null,
    itemName: "Beans",
    imageUrl: "www.hello.com",
    pickupCountry: "Ethiopia",
    deliveryCity: "Washington, DC",
  },
  {
    id: 3,
    authorId: 3,
    claimerId: null,
    itemName: "Chips",
    imageUrl: "www.hello.com",
    pickupCountry: "Ethiopia",
    deliveryCity: "Washington, DC",
  },
  {
    id: 4,
    authorId: 4,
    claimerId: null,
    itemName: "Chips",
    imageUrl: "www.hello.com",
    pickupCountry: "Ethiopia",
    deliveryCity: "Washington, DC",
  },
  {
    id: 5,
    authorId: 5,
    claimerId: null,
    itemName: "Chips",
    imageUrl: "www.hello.com",
    pickupCountry: "Ethiopia",
    deliveryCity: "Washington, DC",
  },
];
