export const posts = [
  {
    id: 1,
    authorId: 1,
    claimerId: null,
    itemName: "Headphones",
    imageUrl:
      "https://281jyfszrx.ufs.sh/f/edYAN59hpaUf6TmUKXQsgjXrm3L29Mb4VviJRxtFqEH7PC5S",
    pickupCountry: "United Kingdom",
    deliveryCity: "Washington, DC",
  },
  {
    id: 2,
    authorId: 2,
    claimerId: null,
    itemName: "Beans",
    imageUrl: "",
    pickupCountry: "Ethiopia",
    deliveryCity: "Washington, DC",
  },
  {
    id: 3,
    authorId: 3,
    claimerId: null,
    itemName: "Crackers",
    imageUrl: "",
    pickupCountry: "Ethiopia",
    deliveryCity: "Washington, DC",
  },
  {
    id: 4,
    authorId: 4,
    claimerId: null,
    itemName: "Chips",
    imageUrl: "",
    pickupCountry: "Ethiopia",
    deliveryCity: "Washington, DC",
  },
  {
    id: 5,
    authorId: 5,
    claimerId: null,
    itemName: "Tea",
    imageUrl: "",
    pickupCountry: "Ethiopia",
    deliveryCity: "Washington, DC",
  },
];
